/**
 * GLB map surfaces: the classifier, the planar UVs, and the detail tiles.
 *
 * The vectors (`glb-surface-vectors.json`) are replayed by
 * `apps/native-fps/src/textures3d.rs` and `world3d.rs`. The rules themselves are
 * one shared file, so what the fixture pins is the *semantics* both sides give
 * it — lowercase, substring, first match — against every material name the
 * bundled maps actually use, read out of the GLBs at generation time.
 *
 *     UPDATE_GLB_SURFACE_VECTORS=1 pnpm --filter @horrible/core test glb-surfaces
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import {
  classifySurface,
  DETAIL_GAIN,
  DETAIL_MEAN,
  planarUv,
  surfaceTileScale,
} from '../glb-surfaces';
import { drawGlbSurfaceTile, normalizeDetailTile } from '../textures3d';

const MAPS_DIR = new URL('../../../../../../backend/modules/hassault/maps/', import.meta.url);
const VECTORS = new URL('./glb-surface-vectors.json', import.meta.url);

function glbMaterialNames(): string[] {
  const names = new Set<string>();
  for (const file of readdirSync(MAPS_DIR)
    .filter((f) => f.endsWith('.glb'))
    .sort()) {
    const buf = readFileSync(new URL(file, MAPS_DIR));
    const jsonLen = buf.readUInt32LE(12);
    const gltf = JSON.parse(buf.subarray(20, 20 + jsonLen).toString('utf8')) as {
      materials?: { name?: string }[];
    };
    for (const m of gltf.materials ?? []) if (m.name) names.add(m.name);
  }
  return [...names].sort();
}

const UV_CASES: [number[], number[], number][] = [
  [[3, 0, 7], [0, 1, 0], 4],
  [[3, 0, 7], [0, -1, 0], 4],
  [[2, 5, 9], [1, 0, 0], 2],
  [[2, 5, 9], [-0.3, 0.2, 0.9], 3],
  // Ties: the shader's `detail_uv` prefers y, then x.
  [[1, 2, 3], [1, 1, 0], 4],
  [[1, 2, 3], [1, 0, 1], 4],
  [[-6, 1.5, 40], [0.5, 0.5, 0.5], 6],
];

const TILE_KINDS = ['masonry', 'plaster', 'cobblestone', 'roof_tile', 'carpet', 'brick'];

function linearMean(tile: Uint8Array): number {
  let sum = 0;
  for (let i = 0; i < tile.length; i += 4) {
    const c = tile[i] / 255;
    sum += c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  }
  return sum / (tile.length / 4);
}

function build() {
  return {
    why: 'Generated by glb-surfaces.test.ts with UPDATE_GLB_SURFACE_VECTORS=1 - do not hand-edit.',
    classify: glbMaterialNames().map((name) => ({ name, kind: classifySurface(name) })),
    uvs: UV_CASES.map(([p, n, scale]) => ({
      p,
      n,
      scale,
      uv: planarUv(p[0], p[1], p[2], n[0], n[1], n[2], scale),
    })),
  };
}

describe('glb surfaces', () => {
  it('matches the vectors the native client replays', () => {
    const got = build();
    if (process.env.UPDATE_GLB_SURFACE_VECTORS) {
      writeFileSync(VECTORS, `${JSON.stringify(got, null, 2)}\n`);
    }
    expect(JSON.parse(readFileSync(VECTORS, 'utf8'))).toEqual(got);
  });

  it('classifies the map materials that used to fall through to concrete', () => {
    expect(classifySurface('mat_sandstone_ochre')).toBe('masonry');
    expect(classifySurface('mat_tuscan_stucco_warm')).toBe('plaster');
    expect(classifySurface('mat_cobblestone_street')).toBe('cobblestone');
    expect(classifySurface('mat_terracotta_roof')).toBe('roof_tile');
    expect(classifySurface('mat_carpet_tile')).toBe('carpet');
    expect(classifySurface('Mat_Brick_Commercial_Red')).toBe('brick');
    // Order matters: each of these contains a later rule's substring too.
    expect(classifySurface('mat_ceiling_tile')).toBe('plaster');
    expect(classifySurface('mat_wood_crate')).toBe('crate');
    expect(classifySurface('mat_sandbag_burlap')).toBe('carpet');
    expect(classifySurface('Mat_LED_Green_Glow')).toBe('none');
    expect(classifySurface('mat_smoked_glass')).toBe('glass');
  });

  it('leaves no bundled map material on the default without a reason', () => {
    // A name that reaches the default is concrete; listing them keeps a new
    // generator material from silently becoming concrete.
    const fallthrough = glbMaterialNames().filter(
      (n) => classifySurface(n) === 'concrete' && !/concrete/i.test(n),
    );
    expect(fallthrough.length).toBeLessThan(40);
  });

  it('projects floors onto xz and walls onto their own plane', () => {
    expect(planarUv(3, 0, 7, 0, 1, 0, 4)).toEqual([0.75, 1.75]);
    expect(planarUv(2, 5, 9, 1, 0, 0, 2)).toEqual([4.5, 2.5]);
    expect(planarUv(2, 5, 9, 0, 0, 1, 1)).toEqual([2, 5]);
    expect(surfaceTileScale('brick')).toBe(2);
  });

  it('normalises every detail tile to the shared mean, grey, and with real contrast', () => {
    expect(DETAIL_MEAN * DETAIL_GAIN).toBeCloseTo(1, 2);
    for (const kind of [...TILE_KINDS, 'concrete', 'wood', 'hazard', 'gold']) {
      const tile = normalizeDetailTile(drawGlbSurfaceTile(kind, 64, 64)!, DETAIL_MEAN);
      expect(linearMean(tile), kind).toBeGreaterThan(DETAIL_MEAN - 0.03);
      expect(linearMean(tile), kind).toBeLessThan(DETAIL_MEAN + 0.03);
      let lo = 255;
      let hi = 0;
      for (let i = 0; i < tile.length; i += 4) {
        expect(tile[i + 1]).toBe(tile[i]);
        lo = Math.min(lo, tile[i]);
        hi = Math.max(hi, tile[i]);
      }
      // Gold is a brushed grain, not a pattern: faint by design.
      expect(hi - lo, kind).toBeGreaterThan(kind === 'gold' ? 8 : 20);
    }
  });

  it('has no generator for the blended kinds', () => {
    expect(drawGlbSurfaceTile('glass')).toBeNull();
    expect(drawGlbSurfaceTile('none')).toBeNull();
  });
});
