"""Generate the Python API reference pages for the dashboard's own SDKs.

    uv run python -m backend.modules.symdex.gen_reference_docs

Writes `docs/reference/python-*.mdx` from the same AST harvest the reference pane
and editor completion read (`extract_sdk`), so the three can never describe
different APIs. `test_python_reference_docs_are_current` fails when the committed
pages differ from what this renders — a docstring edited without regenerating is
caught in CI rather than discovered by a reader.

Docstrings are emitted inside ```text fences, never as prose: MDX evaluates `{…}`
as JSX and parses `<…>` as tags, and a docstring is free text that contains both.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from backend.modules.symdex import reference
from backend.modules.symdex.extract_packages import SymbolDoc
from backend.modules.symdex.extract_sdk import extract_sdk

REPO = Path(__file__).resolve().parents[3]
OUT_DIR = REPO / "docs" / "reference"

PAGES: dict[str, dict[str, str]] = {
    "dash": {
        "file": "python-dash.mdx",
        "title": "dash — the REPL handle",
        "position": "1",
        "intro": (
            "`dash` is seeded into every in-app Python REPL session and scripts the "
            "running dashboard — panes, workspaces, layout, I/O, settings, git — and "
            "every module can add a `dash.<name>` facade (`dash.lens` reads llama.cpp "
            "traces as numpy). "
            "`dash.help()` prints the same list at the prompt. It is a global, not "
            "an importable module: there is no `import dash`. See "
            "[the Python SDK](../architecture/python-sdk.mdx)."
        ),
    },
    "backend.sdk": {
        "file": "python-backend-sdk.mdx",
        "title": "backend.sdk — backend plugins",
        "position": "2",
        "intro": (
            "The server-side plugin contract: routes, agent tools, `/ws` channels, "
            "lifespan hooks, connectors and `dash` facades. See "
            "[the backend plugin SDK](../architecture/backend-plugin-sdk.mdx)."
        ),
    },
    "horrible_train": {
        "file": "python-horrible-train.mdx",
        "title": "horrible_train — the training helper",
        "position": "3",
        "intro": (
            "`import horrible_train as ht` — the dependency-free helper every "
            "generated training notebook uses: `ht.callback()` for metrics that work "
            "offline, `ht.finish()` to close a run. See "
            "[training](../modules/training.mdx)."
        ),
    },
}

HEADER = (
    "{/* Generated by backend/modules/symdex/gen_reference_docs.py — do not edit. "
    "Regenerate with `uv run python -m backend.modules.symdex.gen_reference_docs`. */}"
)


def _full(dist: str, doc: SymbolDoc) -> str:
    fuller = doc.metadata.get("fullDoc")
    if isinstance(fuller, str) and fuller:
        return fuller
    qual = str(doc.metadata.get("qualname") or doc.symbol)
    data = reference.full_doc(
        f"sdk:{dist}", str(doc.metadata.get("module")), qual, None
    )
    return str(data.get("doc") or doc.doc)


def _fence(text: str) -> str:
    # A docstring containing ``` would close the fence early; four backticks cannot
    # appear in one without being very deliberate.
    return f"````text\n{text.rstrip()}\n````"


def render_page(dist: str, docs: list[SymbolDoc]) -> str:
    meta = PAGES[dist]
    groups: OrderedDict[str, list[SymbolDoc]] = OrderedDict()
    for doc in sorted(
        docs, key=lambda d: (str(d.metadata.get("module")), d.kind != "class", d.symbol)
    ):
        groups.setdefault(str(doc.metadata.get("module")), []).append(doc)
    lines = [
        "---",
        f"title: {meta['title']}",
        f"sidebar_position: {meta['position']}",
        "---",
        "",
        HEADER,
        "",
        f"# {meta['title']}",
        "",
        meta["intro"],
        "",
        "Also browsable, with search, in the **Python reference** pane "
        "(`/pydoc`) under *Dashboard SDKs*.",
        "",
    ]
    for module, members in groups.items():
        lines += [f"## `{module}`", ""]
        for doc in members:
            qual = str(doc.metadata.get("qualname") or doc.symbol)
            signature = str(doc.metadata.get("signature") or "")
            label = f"{qual}{signature}" if doc.kind != "class" else f"class {qual}"
            lines += [f"### `{qual}`", "", _fence(label), ""]
            body = _full(dist, doc)
            if body:
                lines += [_fence(body), ""]
            else:
                lines += ["*Undocumented.*", ""]
    return "\n".join(lines).rstrip() + "\n"


def render() -> dict[Path, str]:
    out: dict[Path, str] = {
        OUT_DIR / "_category_.json": (
            '{\n  "label": "Python API reference",\n  "position": 4,\n'
            '  "link": { "type": "generated-index", "description": '
            '"Generated from the source — the dashboard\'s own Python APIs." }\n}\n'
        )
    }
    for harvest in extract_sdk():
        if harvest.dist in PAGES:
            out[OUT_DIR / PAGES[harvest.dist]["file"]] = render_page(
                harvest.dist, harvest.docs
            )
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in render().items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
