import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One autogenerated sidebar over all of docs/. Ordering comes from each page's
// `sidebar_position` frontmatter and the per-folder `_category_.json` files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
