"""Where a finished design goes: into a training project, as a trainable model.

The designer's whole promise is that you leave with a file rather than a dependency,
and this is the last step of that — the generated `nn.Module` lands in the project's
`model.py`, and the project notebook gets a small block that imports and instantiates
it. No new execution path: the same kernel, the same venv, the same Kaggle/Colab push
the training module already has.

Two decisions carry the correctness here, and both are about *not* colliding with the
recipe machinery that already writes into the same notebook:

- **The block has its own marker.** `recipes.apply_to_notebook` finds its previous
  output by `horrible_recipe` cell metadata and replaces everything carrying it. If
  this block used the same flag, regenerating a recipe would delete the model
  definition, and regenerating the model would delete the `SFTConfig` — each silently,
  each discovered only after a wasted run. So this one is `horrible_model`.
- **It lands *before* the recipe block, not after.** A notebook where the trainer is
  configured above the model it trains does not run. Appending is only correct when
  there is nothing to be above.

A regenerate replaces the previous block in place, for the reason recipes does: two
definitions of the same class in one notebook means the second silently wins.
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import BaseModel

from backend.atomic_write import write_text_atomic
from backend.modules.interpretability.graph import codegen
from backend.modules.interpretability.graph.models import DesignGraph
from backend.modules.training.models import ProjectModel

logger = logging.getLogger(__name__)

#: Cell metadata identifying a block this file generated. Deliberately *not*
#: `horrible_recipe` — see the module docstring.
MARKER_KEY = "horrible_model"

#: The header line, which is also the fallback identity for a notebook written
#: before the metadata flag existed, or for cells a user copied by hand.
MARKER_LINE = "## Model — generated by the model designer"

MODULE_FILE = "model.py"


class HandoffResult(BaseModel):
    """What the hand-off did, or why it did nothing."""

    ok: bool = False
    project: str = ""
    #: Where the module was written, when it was.
    modulePath: str = ""
    #: How many notebook cells the block now occupies. Zero with `ok` true means the
    #: module was written but the project has no notebook to wire it into — a real
    #: and reportable outcome, not a failure.
    cells: int = 0
    replaced: bool = False
    className: str = ""
    message: str = ""


def apply(graph: DesignGraph, project: ProjectModel) -> HandoffResult:
    """Write the design into a project as `model.py` plus a notebook block."""
    generated = codegen.generate(graph)
    if generated.error or not generated.source:
        return HandoffResult(
            project=project.id,
            message=(
                "This design does not generate a module yet: "
                f"{generated.error or 'it emits nothing'}."
            ),
        )

    cls = codegen.class_name(graph.name)
    from backend.modules.training import notebooks

    try:
        module_path = notebooks.notebook_path(project, MODULE_FILE)
    except ValueError as exc:  # pragma: no cover - MODULE_FILE is a constant
        return HandoffResult(project=project.id, message=str(exc))

    try:
        write_text_atomic(module_path, generated.source)
    except OSError as exc:
        return HandoffResult(
            project=project.id,
            message=f"Could not write {MODULE_FILE} into the project: {exc}",
        )

    cells, replaced, note = _write_cells(project, cls)
    return HandoffResult(
        ok=True,
        project=project.id,
        modulePath=str(module_path),
        cells=cells,
        replaced=replaced,
        className=cls,
        message=note,
    )


def _write_cells(project: ProjectModel, cls: str) -> tuple[int, bool, str]:
    """Insert or replace the notebook block. Returns (cells, replaced, note)."""
    import nbformat

    from backend.modules.training import notebooks
    from backend.notebook_core import notebooks as core_notebooks

    path = notebooks.notebook_path(project, "main.ipynb")
    try:
        nb = core_notebooks.load(path)
    except (FileNotFoundError, OSError, ValueError) as exc:
        # The module is on disk and importable either way. Saying so beats failing
        # the whole hand-off over a notebook that may not be part of this project.
        logger.info("no notebook to wire %s into: %s", project.id, exc)
        return (
            0,
            False,
            f"{MODULE_FILE} written. This project has no main.ipynb to wire it into.",
        )

    made = [
        nbformat.v4.new_markdown_cell(
            f"{MARKER_LINE}\n\n"
            f"`{MODULE_FILE}` is plain PyTorch and yours to edit. Regenerating from the "
            "designer replaces this block and that file, so keep hand edits elsewhere."
        ),
        nbformat.v4.new_code_cell(
            f"from {MODULE_FILE[:-3]} import {cls}\n"
            "\n"
            f"model = {cls}()\n"
            'print(f"{sum(p.numel() for p in model.parameters()):,} parameters")'
        ),
    ]
    for cell in made:
        cell.metadata[MARKER_KEY] = True

    start = _block_start(nb)
    replaced = start is not None
    if start is None:
        at = _recipe_start(nb)
        # Above the trainer that consumes it, or at the end when there is no trainer.
        if at is None:
            nb.cells.extend(made)
        else:
            nb.cells[at:at] = made
    else:
        end = start
        while end < len(nb.cells) and nb.cells[end].metadata.get(MARKER_KEY):
            end += 1
        nb.cells[start:end] = made

    core_notebooks.save(path, nb)
    return len(made), replaced, ""


def _block_start(nb: Any) -> int | None:
    """Index of a block this file wrote before, if there is one."""
    for index, cell in enumerate(nb.cells):
        if cell.metadata.get(MARKER_KEY):
            return index
        if cell.cell_type == "markdown" and str(cell.source).startswith(MARKER_LINE):
            return index
    return None


def _recipe_start(nb: Any) -> int | None:
    """Index of the recipe block, which the model must be defined above."""
    from backend.modules.training import recipes

    for index, cell in enumerate(nb.cells):
        if cell.metadata.get("horrible_recipe"):
            return index
        if cell.cell_type == "markdown" and str(cell.source).startswith(
            recipes.marker_cell()
        ):
            return index
    return None
